### ISSUE TITLE
Attribute Migration

### ISSUE THREAD

**Issue by Celoain** [netresearch/dhl-module-shipping-core#1]
We've had the old dhl-module-shipping-m2 extension installed and just tried to install the dhl-shipping-m2. 

After removing the deprecated extension we migrated all Attributes (bin/magento dhlgw:migrate-attributes). After this step we are left with this error:
1 exception(s):
`Exception #0 (ReflectionException): Class Dhl\Shipping\Model\Attribute\Backend\TariffNumber does not exist`

We were able to narrow it down to the still existing dhl_tariff_number attribute. Checking with the old module, we saw that we could have used the uninstall method but then it wouldn't be possible to use the migration from the newer module.

Maybe the migration tool should check if these attributes exist and remove the old modules data if that is the case?

**Comment by mam08ixo** [comment]
Hi @Celoain, it is important to execute the attribute migration **before** uninstalling the deprecated module. See [Migration from previous "DHL Versenden" extension](https://github.com/netresearch/dhl-module-carrier-paket/wiki/Documentation-English#migration-from-previous-dhl-versenden-extension).

**Comment by moehrenzahn** [comment]
To recover from your situation, you should be able to reinstall the old extension, restart the attribute migration process, and then uninstall the old extension including all of its data.

**Comment by Celoain** [comment]
> Hi @Celoain, it is important to execute the attribute migration **before** uninstalling the deprecated module. See [Migration from previous "DHL Versenden" extension](https://github.com/netresearch/dhl-module-carrier-paket/wiki/Documentation-English#migration-from-previous-dhl-versenden-extension).

Both modules can't be in the project at the same time due to version conflicts with one of the shared subpackages. (i don't remember which one it was)

So the approach on a production environment would be:
bin/magento maintenance:enable
composer remove dhl/module-shipping-m2
composer require dhl/shipping-m2
bin/magento setup:upgrade
bin/magento s:d:c
bin/magento dhlgw:migrate-attributes
composer remove dhl/shipping-m2
composer require dhl/module-shipping-m2
bin/magento module:uninstall Dhl_Shipping
composer remove dhl/module-shipping-m2
composer require dhl/shipping-m2

I was able to recover from the problem on the dev system but i don't see any seemless way to push this to production.

**Comment by mam08ixo** [comment]
> Both modules can't be in the project at the same time due to version conflicts with one of the shared subpackages. (i don't remember which one it was)

Do you remember which version of the `dhl-module-shipping-m2` extension you had installed when trying to install the new v1.0.0 in parallel?

**Comment by Celoain** [comment]
> Do you remember which version of the `dhl-module-shipping-m2` extension you had installed when trying to install the new v1.0.0 in parallel?

Actually, no. I just tried to install the old module on my dev again just to see if it would work.

> composer require dhl/module-shipping-m2
> Using version ^0.11.1 for dhl/module-shipping-m2
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Can only install one of: dhl/sdk-api-parcel-management[1.0.0, 2.0.0].
>     - Can only install one of: dhl/sdk-api-parcel-management[2.0.0, 1.0.0].
>     - Can only install one of: dhl/sdk-api-parcel-management[1.0.0, 2.0.0].
>     - dhl/module-shipping-m2 0.11.1 requires dhl/sdk-api-parcel-management ^1.0.0 -> satisfiable by dhl/sdk-api-parcel-management[1.0.0].
>     - Installation request for dhl/module-shipping-m2 ^0.11.1 -> satisfiable by dhl/module-shipping-m2[0.11.1].
>     - Installation request for dhl/sdk-api-parcel-management (locked at 2.0.0) -> satisfiable by dhl/sdk-api-parcel-management[2.0.0].
> 
> Installation failed, reverting ./composer.json to its original content.

**Comment by mam08ixo** [comment]
I can only guess that you did not have the latest version of the `dhl-module-shipping-m2` extension installed before installing the new v1.0.0 – which leads to similar issues as described above.

Both extensions in their latest version are compatible with `dhl/sdk-api-parcel-management:1.0.0`, you should not run into conflicts. Now that you already have `dhl/sdk-api-parcel-management:2.0.0` installed ("locked at 2.0.0"), the old extension won't install again.

You will have to downgrade `dhl/sdk-api-parcel-management` to v1.0.0 and try again – or restart from scratch with `dhl/module-shipping-m2:^0.11.0` before installing the `dhl-shipping-m2` metapackage.

Sorry for the inconvenience, your report helps to improve the migration instructions (emphasis on using latest legacy version and executing attribute migration while both extensions are installed).

**Comment by Celoain** [comment]
Okay, i see. Thanks for the explanation. I guess this Issue can stay closed then.
Maybe you could also consider adding a Readme with links to the documentation to the metapackage:
https://github.com/netresearch/dhl-shipping-m2

**Comment by mam08ixo** [comment]
Fair point. The Wiki is already created there but no contents are deployed yet. This will probably be done together with the next metapackage release.

**Comment by ngolatka** [comment]
If anyone runs into this problem in the future: here's a short summary what to do, in [English](https://dhl.support.netresearch.de/support/solutions/articles/12000077379) and in [German](https://dhl.support.netresearch.de/support/solutions/articles/12000077377).
