### ISSUE TITLE
Notify Customer on Shipment creation

### ISSUE THREAD

**Issue by Celoain** [netresearch/dhl-module-shipping-core#2]
When creating a new shipment from the Magento Admin UI with Shipping Label, we have currently the problem that the DHL Shipping Core ignores the Notify Customer option in `Controller/Adminhtml/Order/Shipment/Save.php:122`. Clients are not receiving updates for their order since the send_email option is missing.

Additionally, emails can not be triggered from the Shipment view with the `Send Tracking Information` Button. The Button just stops working as soon as we enable the DHL Shipping Module.

**Comment by ngolatka** [comment]
Hello @Celoain , thanks for reporting this! We'll check what's going on.

**Comment by mam08ixo** [comment]
I can confirm that the _Email Copy of Shipment_ checkbox as well as the _Comment Text_ input are not properly passed through the module code. We will take care of that.

The module does not interfere with the _Send Tracking Information_ functionality though and I was able to send and receive the shipment confirmation email for a DHL order just as expected.

**Comment by ngolatka** [comment]
Closing this for now. Issue should be fixed in version 1.1.0 of dhl-module-shipping-core (which is part of version 1.2.0 of the meta-package dhl-shipping-m2).
