### ISSUE TITLE
Missing label in system.xml

### ISSUE THREAD

**Issue by frostblogNet** [netresearch/dhl-module-shipping-core#4]
dhl/shipping-m2  1.1.0
magento commerce 2.3.4-p2

There is a missing  label in line 18 of the system.xml. Depending on your log level you will see this error in the backend.

Notice: Undefined index: label in /var/www/html/vendor/magento/framework/Data/Form/Element/Multiselect.php on line 81

**Comment by mam08ixo** [comment]
The module does not define any multiselect options via `system.xml`.
Find out which multiselect exactly causes the notice and where the option comes from that has no label.

**Comment by frostblogNet** [comment]
As I told you in Line 18 of the system.xml is a missing label tag. 

https://github.com/netresearch/dhl-module-shipping-core/blob/master/etc/adminhtml/system.xml#L17

I don`t know why magento is using mutiselect here but this is the issue.

**Comment by moehrenzahn** [comment]
@frostblogNet, you are incorrect. `<label>` is not a required element inside `<field>`, and The `shippingCoreInfoBox` field uses a custom frontend model where no label is needed.

The error you see is unrelated to our system.xml file.
