### ISSUE TITLE
Module creates shipping labels too early

### ISSUE THREAD

**Issue by Celoain** [netresearch/dhl-module-shipping-core#5]
The module creates the shipping labels too early. 

reproduce:
1. Create a new Order
2. Invoice that order
3. reduce the Quantity of a product withing to 0 in the catalog management (don't allow Quantity below zero)
4. Try to create a shipment

result:
DHL will have a shipping label but the creation of the shipment in M2 fails

Expected result:
If the M2 Shipment creation fails, automatically delete the DHL Shipping label OR don't create it before the M2 internal checks.

**Comment by mam08ixo** [comment]
Thank you for reporting the issue.

When creating labels using the packaging popup, then the _Magento core_ shipping module does request the shipping label from the carrier web service before creating the shipment. The order of operation is out of control of the carrier module.

If shipment creation fails, I would expect the _Magento core_ module to execute a rollback at the carrier API.

We will try to replicate the issue and investigate why this does not happen. In the worst case, it boils down to a Magento core issue.

**Comment by ngolatka** [comment]
Closing this for now. See the explanation above.
