### ISSUE TITLE
It is not possible to set configuration unde website scope.

### ISSUE THREAD

**Issue by okolya** [netresearch/dhl-module-shipping-core#7]
https://github.com/netresearch/dhl-module-shipping-core/blob/5c556a0f9c5a89cb3677d231f78d841548d6bbff/Block/Adminhtml/System/Config/Form/Field/Package.php#L106

Website id is used as Store id and value could be found. Excpetion blocks complete website

**Comment by mam08ixo** [comment]
Acknowledged, thanks. Will be fixed with the next release.

**Comment by mam08ixo** [comment]
Fixed in version 1.1.5
