### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by antonfries** [netresearch/dhl-module-shipping-core#9]
With the newest update to 2.7.0 i get compilation error:

Class Netresearch\ShippingCore\Api\ReturnShipment\GetDocumentLinksInterface  does not exist

I have an integration of dhl/shipping-m2 in Magento2

Composer log:
      - Upgrading dhl/module-shipping-core (2.0.0 => 2.1.0)
      - Upgrading netresearch/module-shipping-core (2.6.0 => 2.7.0)

**Comment by antonfries** [comment]
Seems like https://github.com/netresearch/module-shipping-ui is not updated yet

`namespace Netresearch\ShippingUi\Component\Listing\Column\Rma;

...
use Netresearch\ShippingCore\Api\ReturnShipment\GetDocumentLinksInterface;

class Documents extends Column`

**Comment by mam08ixo** [comment]
Hi @antonfries, sorry for the inconvenience. Please roll back the two packages until the next [dhl/shipping-m2](https://github.com/netresearch/dhl-shipping-m2) metapackage version is released with all dependencies properly declared. Thank you!

**Comment by mam08ixo** [comment]
[Post & DHL Shipping version 2.5.0](https://github.com/netresearch/dhl-shipping-m2/releases/tag/2.5.0) is available on Marketplace and Packagist. All updated packages should now play nicely together.
